/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppRouter {
    }
    interface FormField {
        "label": string;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface PaginatedForm {
    }
    interface SuccessPage {
    }
}
export interface FormFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormFieldElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppRouterElement extends Components.AppRouter, HTMLStencilElement {
    }
    var HTMLAppRouterElement: {
        prototype: HTMLAppRouterElement;
        new (): HTMLAppRouterElement;
    };
    interface HTMLFormFieldElementEventMap {
        "fieldChange": string;
    }
    interface HTMLFormFieldElement extends Components.FormField, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFormFieldElementEventMap>(type: K, listener: (this: HTMLFormFieldElement, ev: FormFieldCustomEvent<HTMLFormFieldElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFormFieldElementEventMap>(type: K, listener: (this: HTMLFormFieldElement, ev: FormFieldCustomEvent<HTMLFormFieldElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFormFieldElement: {
        prototype: HTMLFormFieldElement;
        new (): HTMLFormFieldElement;
    };
    interface HTMLPaginatedFormElement extends Components.PaginatedForm, HTMLStencilElement {
    }
    var HTMLPaginatedFormElement: {
        prototype: HTMLPaginatedFormElement;
        new (): HTMLPaginatedFormElement;
    };
    interface HTMLSuccessPageElement extends Components.SuccessPage, HTMLStencilElement {
    }
    var HTMLSuccessPageElement: {
        prototype: HTMLSuccessPageElement;
        new (): HTMLSuccessPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-router": HTMLAppRouterElement;
        "form-field": HTMLFormFieldElement;
        "paginated-form": HTMLPaginatedFormElement;
        "success-page": HTMLSuccessPageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppRouter {
    }
    interface FormField {
        "label"?: string;
        "onFieldChange"?: (event: FormFieldCustomEvent<string>) => void;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface PaginatedForm {
    }
    interface SuccessPage {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-router": AppRouter;
        "form-field": FormField;
        "paginated-form": PaginatedForm;
        "success-page": SuccessPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-router": LocalJSX.AppRouter & JSXBase.HTMLAttributes<HTMLAppRouterElement>;
            "form-field": LocalJSX.FormField & JSXBase.HTMLAttributes<HTMLFormFieldElement>;
            "paginated-form": LocalJSX.PaginatedForm & JSXBase.HTMLAttributes<HTMLPaginatedFormElement>;
            "success-page": LocalJSX.SuccessPage & JSXBase.HTMLAttributes<HTMLSuccessPageElement>;
        }
    }
}
